# Generated by Django 4.2.2 on 2023-06-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=19)),
                ('exp_date', models.CharField(max_length=7)),
                ('cvv', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
